name: Update Weather Data

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering

# Add permissions block
permissions:
  contents: write  # Required for pushing changes

jobs:
  update-weather:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper git operations
        token: ${{ secrets.GITHUB_TOKEN }}  # Use the default token
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run update script
      id: update
      run: |
        python "Update Data.py"
        if [ $? -eq 0 ]; then
          echo "status=success" >> $GITHUB_OUTPUT
        else
          echo "status=failure" >> $GITHUB_OUTPUT
          exit 1
        fi
    
    - name: Commit and push if changed
      if: steps.update.outputs.status == 'success'
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add export.csv
        if git diff --quiet && git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update weather data [skip ci]"
          git push
        fi
      continue-on-error: true  # Don't fail the workflow if push fails
    
    - name: Check for errors
      if: failure()
      run: |
        echo "The workflow failed. Check the logs above for details."
        exit 1 